### ISSUE TITLE
stack_trace_formatted is not defined

### ISSUE THREAD

**Issue by raul-casallas** [modzy/grpc-model-template#1]
When I try to use this template it shows an error:

`"UNKNOWN: Exception calling application: name 'stack_trace_formatted' is not defined`

**Comment by bmunday3-zz** [comment]
@raul-casallas Can you please include more details to reproduce this error?

**Comment by raul-casallas** [comment]
I was trying to create a new model, and I have an issue with my `handle_single_input` implementation, so that is causing the other issue, I'm calling this (after starting the container):

`poetry run python grpc_model/src/model_client.py`

And the stack trace that I get is the following one

```
INFO:__main__:Connecting to gRPC server on localhost:45000
INFO:__main__:Sending single input.
Traceback (most recent call last):
  File "grpc_model/src/model_client.py", line 67, in <module>
    run(test_inputs)
  File "grpc_model/src/model_client.py", line 51, in run
    single_response = grpc_client_stub.Run(run_request)
  File "C:\Users\rfcas\AppData\Local\pypoetry\Cache\virtualenvs\grpc-model-bHyahTb5-py3.8\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\rfcas\AppData\Local\pypoetry\Cache\virtualenvs\grpc-model-bHyahTb5-py3.8\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: name 'stack_trace_formatted' is not defined"
        debug_error_string = "{"created":"@1633093119.587000000","description":"Error received from peer ipv6:[::1]:45000","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Exceptio
n calling application: name 'stack_trace_formatted' is not defined","grpc_status":2}"
```

**Comment by raul-casallas** [comment]
``Sorry I forgot the server-side error:

```
INFO:__main__:gRPC Server running on port 45000
INFO:__main__:Model Initialized Successfully.
INFO:__main__:The model is loaded.
Features: Batch Size 8, Adversarial Defence = False, Drift Detection = False, Explainable = False, Retrainable = False
INFO:__main__:Completed call to Status Route in 0.0004222393035888672
CRITICAL:__main__:Traceback (most recent call last):
  File "/opt/app/grpc_model/src/model_server.py", line 218, in Run
    raw_output: Dict[str, bytes] = self.model.handle_single_input(
  File "/opt/app/model_lib/src/model.py", line 119, in handle_single_input
    "output_1.json": json.dumps(process_input(model_input["input_1.txt"]), separators=(",", ":")).encode(),
NameError: name 'process_input' is not defined

ERROR:grpc._server:Exception calling application: name 'stack_trace_formatted' is not defined
Traceback (most recent call last):
  File "/opt/app/grpc_model/src/model_server.py", line 218, in Run
    raw_output: Dict[str, bytes] = self.model.handle_single_input(
  File "/opt/app/model_lib/src/model.py", line 119, in handle_single_input
    "output_1.json": json.dumps(process_input(model_input["input_1.txt"]), separators=(",", ":")).encode(),
NameError: name 'process_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/modzy-user/.local/lib/python3.9/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/opt/app/grpc_model/src/model_server.py", line 227, in Run
    f"Failed to process model input. Exception Encountered: {stack_trace_formatted}"
NameError: name 'stack_trace_formatted' is not defined

```

The first error is mine, I didn't define the process_input method, but the second one is the one that is reporting

**Comment by bmunday3-zz** [comment]
@raul-casallas just committed a fix for this. Please pull down the latest and let me know if you are still experiencing this issue.
